import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type,x-telegram-init-data","Access-Control-Allow-Methods":"GET,POST,OPTIONS"};
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const token=Deno.env.get("TELEGRAM_BOT_TOKEN")!;
const allowed=(Deno.env.get("ADMIN_TELEGRAM_IDS")||"").split(",").map(x=>x.trim()).filter(Boolean);
function out(x,s=200){return new Response(JSON.stringify(x),{status:s,headers:{"Content-Type":"application/json",...cors}})}
async function hm(key,data){const k=await crypto.subtle.importKey("raw",key,{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(data)))}
function hx(b){return Array.from(b).map(x=>x.toString(16).padStart(2,"0")).join("")}
async function auth(raw){if(!token)throw Error("Telegram bot secret is not configured");const p=new URLSearchParams(raw),hash=p.get("hash"),ts=Number(p.get("auth_date")||0);if(!hash||!ts||Math.floor(Date.now()/1000)-ts>86400)throw Error("Invalid or expired Telegram session");const data=Array.from(p.entries()).filter(x=>x[0]!=="hash").sort((a,b)=>a[0].localeCompare(b[0])).map(x=>x[0]+"="+x[1]).join("\n");const secret=await hm(new TextEncoder().encode("WebAppData"),token);if(hx(await hm(secret,data))!==hash)throw Error("Telegram authentication failed");const u=JSON.parse(p.get("user")||"{}");if(!u.id||!allowed.includes(String(u.id)))throw Error("Telegram account is not authorized");return u}
const tables=new Set(["stock_entries","sales_entries","customers","suppliers","employees","employee_attendance","employee_work","production_entries","rate_master"]);
const fields={stock_entries:["material","quantity","unit","amount","supplier","paid_amount","outstanding_amount","payment_status","telegram_user_id"],sales_entries:["material","quantity","unit","selling_price","total_amount","customer","paid_amount","outstanding_amount","payment_status","telegram_user_id"],customers:["name","phone","address","telegram_user_id"],suppliers:["name","phone","address","telegram_user_id"],employees:["employee_id","name","phone","role","wage_type","wage_amount","telegram_user_id"],employee_attendance:["employee_id","attendance_date","status","notes","telegram_user_id"],employee_work:["employee_id","work_date","task","quantity","unit","status","notes","telegram_user_id"],production_entries:["production_date","product","quantity","unit","material_cost","labour_cost","electricity_cost","water_cost","other_cost","employee_id","notes","telegram_user_id"],rate_master:["item_name","rate_type","rate","unit","active","telegram_user_id"]};
function clean(t,d){const o={};for(const k of fields[t]||[])if(d[k]!==undefined)o[k]=d[k];return o}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const user=await auth(req.headers.get("x-telegram-init-data")||"");const b=req.method==="GET"?{}:await req.json();if(b.action==="dashboard"){const count=async t=>{const r=await db.from(t).select("id",{count:"exact",head:true});if(r.error)throw r.error;return r.count||0};return out({stock:await count("stock_entries"),sales:await count("sales_entries"),customers:await count("customers"),employees:await count("employees")})}if(b.action==="list"){const t=String(b.table);if(!tables.has(t))throw Error("Invalid table");const r=await db.from(t).select("*").order("id",{ascending:false}).limit(Math.min(Number(b.limit)||50,100));if(r.error)throw r.error;return out({rows:r.data||[]})}if(b.action==="insert"){const t=String(b.table);if(!tables.has(t))throw Error("Invalid table");const d=clean(t,b.data||{});d.telegram_user_id=String(user.id);if(t==="stock_entries"){d.outstanding_amount=Math.max(0,Number(d.amount||0)-Number(d.paid_amount||0));d.payment_status=Number(d.outstanding_amount)===0?"paid":Number(d.paid_amount||0)>0?"partial":"unpaid"}if(t==="sales_entries"){d.total_amount=Number(d.quantity||0)*Number(d.selling_price||0);d.outstanding_amount=Math.max(0,Number(d.total_amount)-Number(d.paid_amount||0));d.payment_status=Number(d.outstanding_amount)===0?"paid":Number(d.paid_amount||0)>0?"partial":"unpaid"}const r=await db.from(t).insert(d).select("*").single();if(r.error)throw r.error;return out({row:r.data})}if(b.action==="delete"){const t=String(b.table),id=Number(b.id);if(!tables.has(t)||!Number.isInteger(id)||id<1)throw Error("Invalid delete request");const r=await db.from(t).delete().eq("id",id).select("id");if(r.error)throw r.error;if(!r.data?.length)throw Error("Record not found; nothing deleted");return out({deleted:id})}if(b.action==="reports"){const a=await Promise.all([db.from("weekly_turnover").select("*").order("week_start",{ascending:false}).limit(12),db.from("monthly_turnover").select("*").order("month_start",{ascending:false}).limit(12),db.from("customer_receivables").select("*").order("outstanding_amount",{ascending:false}),db.from("supplier_payables").select("*").order("outstanding_amount",{ascending:false})]);for(const r of a)if(r.error)throw r.error;return out({weekly:a[0].data||[],monthly:a[1].data||[],receivables:a[2].data||[],payables:a[3].data||[]})}throw Error("Unknown action")}catch(e){return out({error:e instanceof Error?e.message:String(e)},403)}});